language: node_js
node_js:
  - "12.16.1"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build
before_deploy:
  - zip -r mygymprogress dist package.json server.js
  - mkdir -p dpl_upload
  - mv mygymprogress.zip dpl_upload/mygymprogress.zip
deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    local_dir: dpl_upload
    skip_cleanup: true
    region: "eu-west-2"
    app: "workoutfrontend"
    env: "Workoutfrontend-env"
    bucket_name: "elasticbeanstalk-eu-west-2-345269114307"
    on:
      branch: master
